version: ~> 1.0

os: linux
dist: bionic

language: r

r:
  - "3.6.3"

install:
  - Rscript -e 'install.packages("remotes")'
  
script: 
  - cd /home/travis/build/lordcobisco/covid-br-model-epiforecasts/_nowcasts/covid-regional/
  - travis_wait 60 bash update_nowcasts_cities.sh
